### ISSUE TITLE
Latest PR introduces errors

### ISSUE THREAD

**Issue by rogvidarge** [Teledyne-Marine/pyread7k#17]
# Description
PR #15 introduced an issue running the pytests

# Problem
Removing sonar_settings as a class attribute means that we introduce a break in the pytests.

# Solution
There are two possible solutions here. One is we remove the sonar_settings tests from the test repertoire. The other is we change this line  https://github.com/Teledyne-Marine/pyread7k/blob/f42b00367faa2376d142469ef313e2bfde3d426c/pyread7k/_ping.py#L249 to 
```python
self._offset, self.sonar_settings = offset_record
```

**Comment by gsakkis** [comment]
Another possible solution: save `self.sonar_settings` if (and only if) running the tests. If you are using `pytest`, there are several [possible ways to detect it](https://stackoverflow.com/questions/25188119/test-if-code-is-executed-from-within-a-py-test-session). 

`SonarSettings` is a large dataclass, if it's not needed outside the tests ideally it shouldn't be stored.

**Comment by rasmus-klett-tele** [comment]
As I commented on your PR review, sonar settings is an essential record to the Ping class, and we use its contents in basically every experiment we run. So we unfortunately have to store it. Additionally it is used for intializing the ping, which is why we just tie it to the ping in `__init__`. 

If we really wanted to save that memory, we could drop it after initialization and then re-load it on demand if needed, but I really don't think that is worth it, considering how often it is needed.

**Comment by gsakkis** [comment]
I see, I thought it was used only internally in the `Ping` class (and the tests). How about adding a `sonar_settings` property so that it's obvious is part of the public API and storing the attribute as `_sonar_settings`? 

Btw it can be computed dynamically as and exposed as a (cached) property if desired:
```
    @cached_property
    def sonar_settings(self) -> records.SonarSettings:
        return cast(records.SonarSettings, self._read_record(7000))
```

**Comment by rasmus-klett-tele** [comment]
As I said, I don't see a reason to use the dynamic loading since we need the data at init anyway, and it's not that big anyway.

Wrapping it in a property seems redundant to me. In the old setup it will show up just fine in the interpreter `help()` and any autogenerated docs we might have in the future. I understand why you were confused about it digging into the source code, but I don't think it's a problem for users. I might be wrong though. @rogvidarge  What do you think?
