### ISSUE TITLE
Record set problems on last ping of multi file s7k datasets

### ISSUE THREAD

**Issue by rogvidarge** [Teledyne-Marine/pyread7k#24]
# Problem
On the record sets such velocity set and heading set there is an issue on the last ping in a file resulting in to many records associations. According to analysis by Jesper, this issue is not present when he iteratively walks through the record, i.e. it must be an issue occuring because of how we associate velocity set records with pings.

## Examples: Velocity Set Issue
Below is a visualization of the velocity set timestamps. The visualization is from two s7k files, where color distinguishes the files, the red large markers are the times associated with the 7018 record, and the lines show the duration of data associated with a pings velocity set.
![velocity_issues](https://user-images.githubusercontent.com/74651486/149518709-f8e1a0e6-32b7-4237-9807-dd0266152981.png)

## Example: Heading Set Issue
Below is a similar visualization of the heading set timestamps. See above example for details.
![headingset_issue](https://user-images.githubusercontent.com/74651486/149527348-6708ab0b-eea6-4903-9748-f02304f28796.png)

## Example: Iterative Record Parsing
Below is a visualization of the same 
![image](https://user-images.githubusercontent.com/74651486/149519063-6b42c7d1-dc6e-4f61-842b-022804cc2cd3.png)

# Solution
Fix it in the FolderDataset class, where we already are removing duplicate pings. This could be as simple as capping record sets to the timestamp of the next ping.

**Comment by rasmus-klett-tele** [comment]
I have investigated this problem before. The issue arises from the logging program that slices a long recording into 1gb files. Whenever it starts a new file, it will (by design!) duplicate a period of motion data. This is done for "context" so that you can take a single file for analysis, and you will usually have all the motion data you need.

The problem with our implementation is that we read each file independently. Each Ping object will read motion data from its own timestamp and till the next Ping's timestamp. The final ping of the file does not have a "next ping", and will therefore read till the end of the file. 

This could be solved in the FolderDataset by taking the timestamp of the first ping of each FileDataset, and passing it back to the last ping of the previous FileDataset. This creates a dependency between files which is a little unfortunate, but I think it is the correct solution, since the problem is that these files fundamentally are not independent.

This solution has a problem when the input is not a sequence of files from the same recording. If you give it a folder of mixed 7k files not from the same recording, we must handle this somehow, by not doing this. I'm not sure what the best solution is technically. Either we must detect whether files are from the same recording, or we must split FolderDataset into two, so that we have a new SequentialFilesDataset with this behaviour.

**Comment by rasmus-klett-tele** [comment]
Oops! Not sure how I managed to close that for a moment..
